sudo: false
language: node_js
node_js:
- '8'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
- cd client
- npm update
- cd ../
install:
- npm install
- cd client
- npm install
- cd ../
script:
- npm test
- cd client
- npm test